# Generated by Django 3.0.8 on 2020-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(default='*', max_length=2056),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
