# Generated by Django 3.0.8 on 2020-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201223_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
